export { default as TabNewsActive } from './svg/ic_tab_news_active.svg';
export { default as TabNews } from './svg/ic_tab_news_inactive.svg';
export { default as TabCollectionActive } from './svg/ic_tab_collection_active.svg';
export { default as TabCollection } from './svg/ic_tab_collection_inactive.svg';
export { default as TabSearch } from './svg/ic_tab_search_inactive.svg';
export { default as TabSearchActive } from './svg/ic_tab_search_active.svg';
export { default as TabGuideActive } from './svg/ic_tab_guide_active.svg';
export { default as TabGuide } from './svg/ic_tab_guide_inactive.svg';
export { default as TabProfileActive } from './svg/ic_tab_profile_active.svg';
export { default as TabProfile } from './svg/ic_tab_profile_inactive.svg';
export { default as TabCity } from './svg/ic_city_inactive.svg';
export { default as TabCityActive } from './svg/ic_city_active.svg';
export { default as TabBookmarkActive } from './svg/ic_bookmarks_active.svg';
export { default as TabBookmark } from './svg/ic_bookmarks.svg';
export { default as TabInfo } from './svg/ic_city_info.svg';
export { default as TabInfoActive } from './svg/ic_city_info_active.svg';
export { default as SearchCityActive } from './svg/ic_search_city_active.svg';
export { default as FaceId } from './svg/ic_faceid.svg';
export { default as BookmarkWhite } from './svg/ic_bookmarks_white.svg';
export { default as TransportMap } from './svg/img_map.svg';
export { default as ICSee } from './svg/ic_see_cat.svg';
export { default as ICEat } from './svg/ic_eat_cat.svg';
export { default as ICDrink } from './svg/ic_drink_cat.svg';
export { default as ICEntertaiment } from './svg/ic_entertaiment_cat.svg';
export { default as ICClub } from './svg/ic_night_club_cat.svg';
export { default as ICSleep } from './svg/ic_sleep_cat.svg';
export { default as ICShopping } from './svg/ic_shopping_cat.svg';
export { default as ICMedical } from './svg/ic_medical_cat.svg';
export { default as ICBank } from './svg/ic_bank_cat.svg';
export { default as ICTransport } from './svg/ic_transport.svg';
export { default as ICExchange } from './svg/ic_exchange.svg';
export { default as ICWeather } from './svg/ic_cloudy_heavy_rain.svg';
export { default as ICChange } from './svg/ic_change.svg';
export { default as ICAir } from './svg/ic_air_humidity.svg'
export { default as ICWind } from './svg/ic_wind_speed.svg'
export { default as ICWeatherSun } from './svg/ic_weather_sun.svg'
export { default as ICUmbrella } from './svg/ic_rain.svg'

