     @ptomasroos/react-native-multi-slider 
     @react-native-community/blur 
     @react-native-community/datetimepicker 
     @react-native-community/netinfo 
     @react-native-masked-view/masked-view 
     @react-navigation/bottom-tabs 
     @react-navigation/material-top-tabs
     @react-navigation/native 
     @react-navigation/stack 
     @shopify/flash-list 
     babel-plugin-module-resolver 
     lodash 
     metro-react-native-babel-preset 
     moment 

     react-native-action-button 
     react-native-bootsplash 
     react-native-calendars 
     react-native-circular-action-menu
     react-native-geolocation-service 
     react-native-gesture-handler 
     react-native-hyperlink 
     react-native-image-picker 
     react-native-iphone-x-helper 
     react-native-keyboard-aware-scroll-view 
     react-native-linear-gradient 
     react-native-maps 
     react-native-maps-directions 
     react-native-material-menu 
     react-native-material-ripple 
     react-native-media-controls 
     react-native-pager-view 
     react-native-ratings 
     react-native-reanimated 
     react-native-render-html 
     react-native-responsive-fontsize 
     react-native-safe-area-context 
     react-native-screens 
     react-native-slider 
     react-native-snap-carousel 
     react-native-svg 
     react-native-svg-transformer 
     react-native-swipe-list-view 
     react-native-swiper 
     react-native-tab-view 
     react-native-textinput-effects 
     react-native-ui-lib 
     react-native-unimodules 
     react-native-video 
     react-native-webview 
     victory-native  