const Routes = {
  MainBottomTab: 'MainBottomTab',
  Onboarding: 'Onboarding',
  Walkthrough: 'Walkthrough',
  Login: 'Login',
  ForgotPassword: 'ForgotPassword',
  ResetPassword: 'ResetPassword',
  ResetSuccess: 'ResetSuccess',
  Signup: 'Signup',
  NewsFeed: 'NewsFeed',
  PublicTripStep1: 'PublicTripStep1',
  PublicTripStep2: 'PublicTripStep2',
  UploadTripCover: 'UploadTripCover',
  WriteContent: 'WriteContent',
  // UploadTripCoverCompleted:'UploadTripCoverCompleted',
  PublicTripStep3: 'PublicTripStep3',
  AddPlace:'AddPlace',
  // WriteContentLocationAdded:'WriteContentLocationAdded',
  // AddTripPhotos:'AddTripPhotos',
  ShareToFriend:'ShareToFriend',
  Search: 'Search',
  Profile: 'Profile',
  Collection: 'Collection',
  Guide: 'Guide',
  Setting: 'Setting',
  UpdateProfile: 'UpdateProfile',
  SettingStack: 'SettingStack',
  Notification: 'Notification',
  InboxList: 'InboxList',
  Follow: 'Follow',
  ChatBox: 'ChatBox',
  GuideDetailTab: 'GuideDetailTab',
  TravelGuide: 'Travel Guide',
  City: 'City',
  Information: 'Information',
  SearchTravelGuide: 'SearchTravelGuide',
  Bookmarks: 'Bookmarks',
  ExchangeMoney: 'ExchangeMoney',
  Weather: 'Weather',
  Transport: 'Transport',
  CityStack: 'CityStack',
  CityMap: 'CityMap',
  CityListPlace: 'CityListPlace',
  Filter: 'Filter',
  PlaceDetail: 'PlaceDetail',
  Find: 'Find',
  Map: 'Map',
  TravelActivity: 'TravelActivity',
  TravelActivityDetail: 'TravelActivityDetail',
  SearchTravelResult: 'SearchTravelResult',
  PlaceToVisit: 'PlaceToVisit',
  ReviewScreen: 'ReviewScreen',
  CreateReview: 'CreateReview',
  TripCover: 'TripCover',
  TripDetail: 'TripDetail',
  ProfileStack: 'ProfileStack',
  TripComment: 'TripComment',
  HotelAround: 'HotelAround',
  HotelList: 'HotelList',
  TripRoutes: 'TripRoutes',
  RouteDetail: 'RouteDetail',
  ImageQuote: 'ImageQuote'
};

export const Tabs = {
  MainTab: 'MainTab',
  CityGuideTab: 'CityGuideTab',
};

export default Routes;
